# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.check_pb2 as check__pb2
import protos.ic20_module_createstate_pb2 as ic20__module__createstate__pb2


class Module_CreateStateStub(object):
  """The module service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.create_state = channel.unary_unary(
        '/IC20.Modules.GrpcService.Protos.Module_CreateState/create_state',
        request_serializer=ic20__module__createstate__pb2.create_state_Params.SerializeToString,
        response_deserializer=ic20__module__createstate__pb2.State.FromString,
        )
    self.Initialize = channel.unary_unary(
        '/IC20.Modules.GrpcService.Protos.Module_CreateState/Initialize',
        request_serializer=check__pb2.ExecuteRequest.SerializeToString,
        response_deserializer=check__pb2.ExecuteResponse.FromString,
        )


class Module_CreateStateServicer(object):
  """The module service definition.
  """

  def create_state(self, request, context):
    """Sends an Execute command
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Initialize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_Module_CreateStateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'create_state': grpc.unary_unary_rpc_method_handler(
          servicer.create_state,
          request_deserializer=ic20__module__createstate__pb2.create_state_Params.FromString,
          response_serializer=ic20__module__createstate__pb2.State.SerializeToString,
      ),
      'Initialize': grpc.unary_unary_rpc_method_handler(
          servicer.Initialize,
          request_deserializer=check__pb2.ExecuteRequest.FromString,
          response_serializer=check__pb2.ExecuteResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'IC20.Modules.GrpcService.Protos.Module_CreateState', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
