# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ic20_module_createstate.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.check_pb2 as check__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ic20_module_createstate.proto',
  package='IC20.Modules.GrpcService.Protos',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1dic20_module_createstate.proto\x12\x1fIC20.Modules.GrpcService.Protos\x1a\x0b\x63heck.proto\"\x16\n\x05State\x12\r\n\x05state\x18\x01 \x01(\t\"(\n\x13\x63reate_state_Params\x12\x11\n\tStateInit\x18\x01 \x01(\t2\xf7\x01\n\x12Module_CreateState\x12n\n\x0c\x63reate_state\x12\x34.IC20.Modules.GrpcService.Protos.create_state_Params\x1a&.IC20.Modules.GrpcService.Protos.State\"\x00\x12q\n\nInitialize\x12/.IC20.Modules.GrpcService.Protos.ExecuteRequest\x1a\x30.IC20.Modules.GrpcService.Protos.ExecuteResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[check__pb2.DESCRIPTOR,])




_STATE = _descriptor.Descriptor(
  name='State',
  full_name='IC20.Modules.GrpcService.Protos.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='IC20.Modules.GrpcService.Protos.State.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=101,
)


_CREATE_STATE_PARAMS = _descriptor.Descriptor(
  name='create_state_Params',
  full_name='IC20.Modules.GrpcService.Protos.create_state_Params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='StateInit', full_name='IC20.Modules.GrpcService.Protos.create_state_Params.StateInit', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['create_state_Params'] = _CREATE_STATE_PARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'ic20_module_createstate_pb2'
  # @@protoc_insertion_point(class_scope:IC20.Modules.GrpcService.Protos.State)
  })
_sym_db.RegisterMessage(State)

create_state_Params = _reflection.GeneratedProtocolMessageType('create_state_Params', (_message.Message,), {
  'DESCRIPTOR' : _CREATE_STATE_PARAMS,
  '__module__' : 'ic20_module_createstate_pb2'
  # @@protoc_insertion_point(class_scope:IC20.Modules.GrpcService.Protos.create_state_Params)
  })
_sym_db.RegisterMessage(create_state_Params)



_MODULE_CREATESTATE = _descriptor.ServiceDescriptor(
  name='Module_CreateState',
  full_name='IC20.Modules.GrpcService.Protos.Module_CreateState',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=146,
  serialized_end=393,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_state',
    full_name='IC20.Modules.GrpcService.Protos.Module_CreateState.create_state',
    index=0,
    containing_service=None,
    input_type=_CREATE_STATE_PARAMS,
    output_type=_STATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Initialize',
    full_name='IC20.Modules.GrpcService.Protos.Module_CreateState.Initialize',
    index=1,
    containing_service=None,
    input_type=check__pb2._EXECUTEREQUEST,
    output_type=check__pb2._EXECUTERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODULE_CREATESTATE)

DESCRIPTOR.services_by_name['Module_CreateState'] = _MODULE_CREATESTATE

# @@protoc_insertion_point(module_scope)
